# no version needed; auto-derived

services:
  php82-fpm:
    build:
      context: . # better that "" or ./
      dockerfile: Dockerfile
    container_name: php82-fpm-container
    restart: always
    working_dir: /var/www # no trailling /
    volumes:
      - ../:/var/www
    networks:
      - nginx-php-pg-network
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: always
    depends_on:
      - php82-fpm
    ports:
      - "8000:80" # using strings for "<port-mapping>"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - nginx-php-pg-network
    
  postgres:
    image: postgres:16-alpine
    container_name: postgres-container
    restart: always
    environment:
    # use --env-file flag on docker compose
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # inside docker/ dir, there will be created storage/postgresql:
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432" # optional: expose to host
    networks:
      - nginx-php-pg-network


# adding network is best practice
networks:
  nginx-php-pg-network:

# if the DB volume was NAMED, like: "pgdata" for example,
# we need a last section of:
# ---------
# volumes:
#   pgdata:
#----------
